apiVersion: v1
kind: Service
metadata:
  name: world-service
  labels:
    app: world-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: world-service
