name: 'Publish Container'
description: 'Build and publish a container'
inputs:
  context:
    description: 'Docker context'
    required: false
    default: .
  dockerfile:
    description: 'Dockerfile path'
    required: true
  image-name:
    description: 'Image name'
    required: true
  registry:
    description: 'Docker registry'
    required: false
    default: 'ghcr.io'
  github-token:
    description: GitHub token
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
